//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos_Materiales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materiales()
        {
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public decimal id_materiales { get; set; }
        public string nombre { get; set; }
        public decimal id_tipo { get; set; }
        public decimal cantidad { get; set; }
        public decimal costo { get; set; }
    
        public virtual Tipos Tipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}
