//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos_Materiales
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecursosEntities : DbContext
    {
        public RecursosEntities()
            : base("name=RecursosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Edificios> Edificios { get; set; }
        public virtual DbSet<Materiales> Materiales { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<Tipos> Tipos { get; set; }
        public virtual DbSet<VW_Edificios_departamentos> VW_Edificios_departamentos { get; set; }
        public virtual DbSet<VW_Materiales_Tipos> VW_Materiales_Tipos { get; set; }
        public virtual DbSet<VW_Pedidos_departamentos_material> VW_Pedidos_departamentos_material { get; set; }
    }
}
