//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos_Materiales
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Edificios_departamentos
    {
        public string nombre_departamento { get; set; }
        public string nombre_encargado { get; set; }
        public string nombre { get; set; }
    }
}
