//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos_Materiales
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Materiales_Tipos
    {
        public decimal id_materiales { get; set; }
        public string nombre { get; set; }
        public string caracteristica { get; set; }
        public decimal cantidad { get; set; }
        public decimal costo { get; set; }
    }
}
