//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos_Materiales
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Pedidos_departamentos_material
    {
        public decimal id { get; set; }
        public System.DateTime fecha_pedido { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public string nombre { get; set; }
        public string nombre_departamento { get; set; }
        public string status { get; set; }
        public decimal cantidad { get; set; }
    }
}
